plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.haviq.richmusic'
    compileSdk 36

    defaultConfig {
        applicationId "com.haviq.richmusic"
        minSdk 24
        targetSdk 36
        versionCode 70
        versionName "4.8"
    }
    lint {
        checkReleaseBuilds false
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

repositories {
    maven { url 'https://jitpack.io' }
}

dependencies {
// v0.26.5 is blocked by YouTube's new PO Token requirements.
// Updating to the latest stable Extractor to fix broken music playback.
// NOTE: Extractor development shifted away from tags, we use a specific commit hash
implementation "com.github.TeamNewPipe:NewPipeExtractor:13a655fe"
implementation "com.google.android.gms:play-services-ads:23.6.0"
implementation "androidx.core:core-ktx:1.15.0"
implementation "androidx.appcompat:appcompat:1.7.1"
implementation "androidx.webkit:webkit:1.12.1"
implementation "androidx.media3:media3-exoplayer:1.5.1"
implementation "androidx.media3:media3-session:1.5.1"
implementation "androidx.media3:media3-ui:1.5.1"
implementation "androidx.media:media:1.7.0"
implementation "com.google.code.gson:gson:2.11.0"
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
}
